update ubuntu build scripts

diff --git a/scripts/ubuntu b/scripts/ubuntu
--- a/scripts/ubuntu
+++ b/scripts/ubuntu
@@ -1,33 +1,47 @@
 #!/bin/sh
 
-set -exuo pipefail
+set -ex
 
+# Load VERSION_CODENAME to use when adding apt repos
 . /etc/os-release
 
-cat <<EOF > /etc/apt/sources.list.d/ubuntu.sources
-Types: deb
-URIs: http://archive.ubuntu.com/ubuntu
-Suites: ${VERSION_CODENAME} ${VERSION_CODENAME}-updates ${VERSION_CODENAME}-backports
-Components: main universe restricted multiverse
-Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
+## Save this for later because future ubuntu versions will require this format
+# cat <<EOF > /etc/apt/sources.list.d/ubuntu.sources
+# Types: deb
+# URIs: http://archive.ubuntu.com/ubuntu
+# Suites: ${VERSION_CODENAME} ${VERSION_CODENAME}-updates ${VERSION_CODENAME}-backports
+# Components: main universe restricted multiverse
+# Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
 
-## Ubuntu security updates. Aside from URIs and Suites,
-## this should mirror your choices in the previous section.
-Types: deb
-URIs: http://security.ubuntu.com/ubuntu
-Suites: ${VERSION_CODENAME}-security
-Components: main universe restricted multiverse
-Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
+# ## Ubuntu security updates. Aside from URIs and Suites,
+# ## this should mirror your choices in the previous section.
+# Types: deb
+# URIs: http://security.ubuntu.com/ubuntu
+# Suites: ${VERSION_CODENAME}-security
+# Components: main universe restricted multiverse
+# Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
+# EOF
+
+# Add updates, security, and backports
+cat <<EOF > /etc/apt/sources.list
+deb http://archive.ubuntu.com/ubuntu/ ${VERSION_CODENAME} main restricted universe multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${VERSION_CODENAME}-updates main restricted universe multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${VERSION_CODENAME}-security main restricted universe multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${VERSION_CODENAME}-backports main restricted universe multiverse
 EOF
 
-DEBIAN_FRONTEND=noninteractive
-
+APT_OPTS='Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
+export DEBIAN_FRONTEND=noninteractive
 apt update
-apt upgrade -y
+apt upgrade -y -o $APT_OPTS
+apt install -y -o $APT_OPTS net-tools openssh-server iputils-ping vim less nano micro ca-certificates sudo iptables
 
-apt install -y net-tools openssh-server iputils-ping vim less nano micro ca-certificates
+systemctl enable ssh
 
+# apt cleanup
 rm -rf /var/cache/apt/archives
-
 apt clean
+apt autoremove
 
+# add phenix hostname
+echo '127.0.1.1 phenix' > /etc/hosts
