fix ubuntu build and lock phenix version

diff --git a/scripts/ubuntu-user b/scripts/ubuntu-user
--- a/scripts/ubuntu-user
+++ b/scripts/ubuntu-user
@@ -2,7 +2,8 @@
 
 set -ex
 
-useradd --create-home --shell /bin/bash ubuntu
+# don't fail if user already exists
+useradd --create-home --shell /bin/bash ubuntu || true
 usermod -aG sudo ubuntu
 echo 'ubuntu   ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/ubuntu
 echo 'ubuntu:ubuntu' | chpasswd
